---
- name: Installation Apache / HTTP services 
  hosts: all
  become: true
  tasks:
            - name: install apache & PHP packages
              package:
                      update_cache: yes
                      name:
                              - "{{ apache_package }}"
                              - "{{ php_package }}"
                      state: latest
