---
- hosts: all
  name: update repository index
  become: true
  tasks:

          - name: update repository index
            apt:
                    update_cache: yes
          
          - name: install qemu guest agent package
            apt:
                    name: qemu-guest-agent
                    state: present  
